import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./component/Footer/page";
import NavBar from "./component/NavBar/page";
import ClientProvider from "./redux/store/ClientProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "e-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider>
          <NavBar cartCount={0} />
          {children}
          <Footer />
        </ClientProvider>
      </body>
    </html>
  );
}
